### ISSUE TITLE
Choosing a WC from System UI

### ISSUE THREAD

**Issue by iggy14750** [TrainingMontage/test#59]
In order for a user to identify a WC from our system UI, we'll display a drop-down menu with the ranges of blocks which this WC controls. I will implement a method which constructs and returns all of these strings.  For example, `5...15, 27...32, 45...51` represents a WC which has control over all of the blocks listed. When a user chooses one of these options, details of internal behavior is still TBD.

**Comment by AlecRosenbaum** [comment]
Is there any update on this?
